
using System;
using System.Collections.Generic;
using System.Text;

namespace seq.Domain.Entities
{
    public class GeralDetalheModel
    {
        public long DetalheId { get; set; }
        public Guid HeaderIdPai { get; set; }
        public int Linha { get; set; }
        public string Campo001 { get; set; }
        public string Campo002 { get; set; }
        public string Campo003 { get; set; }
        public string Campo004 { get; set; }
        public string Campo005 { get; set; }
        public string Campo006 { get; set; }
        public string Campo007 { get; set; }
        public string Campo008 { get; set; }
        public string Campo009 { get; set; }
        public string Campo010 { get; set; }
        public string Campo011 { get; set; }
        public string Campo012 { get; set; }
        public string Campo013 { get; set; }
        public string Campo014 { get; set; }
        public string Campo015 { get; set; }
        public string Campo016 { get; set; }
        public string Campo017 { get; set; }
        public string Campo018 { get; set; }
        public string Campo019 { get; set; }
        public string Campo020 { get; set; }
        public string Campo021 { get; set; }
        public string Campo022 { get; set; }
        public string Campo023 { get; set; }
        public string Campo024 { get; set; }
        public string Campo025 { get; set; }
        public string Campo026 { get; set; }
        public string Campo027 { get; set; }
        public string Campo028 { get; set; }
        public string Campo029 { get; set; }
        public string Campo030 { get; set; }
        public string Campo031 { get; set; }
        public string Campo032 { get; set; }
        public string Campo033 { get; set; }
        public string Campo034 { get; set; }
        public string Campo035 { get; set; }
        public string Campo036 { get; set; }
        public string Campo037 { get; set; }
        public string Campo038 { get; set; }
        public string Campo039 { get; set; }
        public string Campo040 { get; set; }
        public string Campo041 { get; set; }
        public string Campo042 { get; set; }
        public string Campo043 { get; set; }
        public string Campo044 { get; set; }
        public string Campo045 { get; set; }
        public string Campo046 { get; set; }
        public string Campo047 { get; set; }
        public string Campo048 { get; set; }
        public string Campo049 { get; set; }
        public string Campo050 { get; set; }
        public string Campo051 { get; set; }
        public string Campo052 { get; set; }
        public string Campo053 { get; set; }
        public string Campo054 { get; set; }
        public string Campo055 { get; set; }
        public string Campo056 { get; set; }
        public string Campo057 { get; set; }
        public string Campo058 { get; set; }
        public string Campo059 { get; set; }
        public string Campo060 { get; set; }
        public string Campo061 { get; set; }
        public string Campo062 { get; set; }
        public string Campo063 { get; set; }
        public string Campo064 { get; set; }
        public string Campo065 { get; set; }
        public string Campo066 { get; set; }
        public string Campo067 { get; set; }
        public string Campo068 { get; set; }
        public string Campo069 { get; set; }
        public string Campo070 { get; set; }
        public string Campo071 { get; set; }
        public string Campo072 { get; set; }
        public string Campo073 { get; set; }
        public string Campo074 { get; set; }
        public string Campo075 { get; set; }
        public string Campo076 { get; set; }
        public string Campo077 { get; set; }
        public string Campo078 { get; set; }
        public string Campo079 { get; set; }
        public string Campo080 { get; set; }
        public string Campo081 { get; set; }
        public string Campo082 { get; set; }
        public string Campo083 { get; set; }
        public string Campo084 { get; set; }
        public string Campo085 { get; set; }
        public string Campo086 { get; set; }
        public string Campo087 { get; set; }
        public string Campo088 { get; set; }
        public string Campo089 { get; set; }
        public string Campo090 { get; set; }
        public string Campo091 { get; set; }
        public string Campo092 { get; set; }
        public string Campo093 { get; set; }
        public string Campo094 { get; set; }
        public string Campo095 { get; set; }
        public string Campo096 { get; set; }
        public string Campo097 { get; set; }
        public string Campo098 { get; set; }
        public string Campo099 { get; set; }
        public string Campo100 { get; set; }
        public string Campo101 { get; set; }
        public string Campo102 { get; set; }
        public string Campo103 { get; set; }
        public string Campo104 { get; set; }
        public string Campo105 { get; set; }
        public string Campo106 { get; set; }
        public string Campo107 { get; set; }
        public string Campo108 { get; set; }
        public string Campo109 { get; set; }
        public string Campo110 { get; set; }
        public string Campo111 { get; set; }
        public string Campo112 { get; set; }
        public string Campo113 { get; set; }
        public string Campo114 { get; set; }
        public string Campo115 { get; set; }
        public string Campo116 { get; set; }
        public string Campo117 { get; set; }
        public string Campo118 { get; set; }
        public string Campo119 { get; set; }
        public string Campo120 { get; set; }
        public string Campo121 { get; set; }
        public string Campo122 { get; set; }
        public string Campo123 { get; set; }
        public string Campo124 { get; set; }
        public string Campo125 { get; set; }
        public string Campo126 { get; set; }
        public string Campo127 { get; set; }
        public string Campo128 { get; set; }
        public string Campo129 { get; set; }
        public string Campo130 { get; set; }
        public string Campo131 { get; set; }
        public string Campo132 { get; set; }
        public string Campo133 { get; set; }
        public string Campo134 { get; set; }
        public string Campo135 { get; set; }
        public string Campo136 { get; set; }
        public string Campo137 { get; set; }
        public string Campo138 { get; set; }
        public string Campo139 { get; set; }
        public string Campo140 { get; set; }
    }
}
