using seq.Domain.Interface.Entities.Geral;
using System;
using System.Collections.Generic;
using System.Text;

namespace seq.Domain.Entities.Geral
{
    public class GeralDetalheModel : IGeralDetalheModel
    {
        public long DetalheId { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public long HeaderId { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo001 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo002 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo003 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo004 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo005 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo006 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo007 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo008 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo009 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo010 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo011 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo012 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo013 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo014 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo015 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo016 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo017 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo018 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo019 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo020 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo021 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo022 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo023 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo025 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo026 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo027 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo028 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo029 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo030 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo031 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo032 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo033 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo034 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo035 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo036 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo037 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo038 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo039 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo040 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo041 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo042 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo043 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo044 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo045 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo046 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo047 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo048 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo049 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo050 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo051 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo052 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo053 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo054 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo055 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo056 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo057 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo058 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo059 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo060 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo061 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo062 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo063 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo064 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo065 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo066 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo067 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo068 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo069 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo070 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo071 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo072 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo073 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo074 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo075 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo076 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo077 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo078 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo079 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo080 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo081 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo082 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo083 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo084 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo085 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo086 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo087 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo088 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo089 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo090 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo091 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo092 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo093 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo094 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo095 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo096 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo097 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo098 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo099 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo100 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo101 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo102 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo103 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo104 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo105 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo106 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo107 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo108 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo109 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo110 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo111 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo112 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo113 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo114 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo115 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo116 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo117 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo118 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo119 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo120 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo121 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo122 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo123 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo124 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo125 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo126 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo127 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo128 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo129 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo130 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo131 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo132 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo133 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo134 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo135 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo136 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo137 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo138 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo139 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
        public string Campo140 { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
    }
}
