using System;
using System.Collections.Generic;
using System.Text;

namespace seq.Domain.Interface.Entities.Geral
{
    public interface IGeralDetalheModel
    {
        long DetalheId { get; set; }
        long HeaderId { get; set; }
        string Campo001 { get; set; }
        string Campo002 { get; set; }
        string Campo003 { get; set; }
        string Campo004 { get; set; }
        string Campo005 { get; set; }
        string Campo006 { get; set; }
        string Campo007 { get; set; }
        string Campo008 { get; set; }
        string Campo009 { get; set; }
        string Campo010 { get; set; }
        string Campo011 { get; set; }
        string Campo012 { get; set; }
        string Campo013 { get; set; }
        string Campo014 { get; set; }
        string Campo015 { get; set; }
        string Campo016 { get; set; }
        string Campo017 { get; set; }
        string Campo018 { get; set; }
        string Campo019 { get; set; }
        string Campo020 { get; set; }
        string Campo021 { get; set; }
        string Campo022 { get; set; }
        string Campo023 { get; set; }
        string Campo025 { get; set; }
        string Campo026 { get; set; }
        string Campo027 { get; set; }
        string Campo028 { get; set; }
        string Campo029 { get; set; }
        string Campo030 { get; set; }
        string Campo031 { get; set; }
        string Campo032 { get; set; }
        string Campo033 { get; set; }
        string Campo034 { get; set; }
        string Campo035 { get; set; }
        string Campo036 { get; set; }
        string Campo037 { get; set; }
        string Campo038 { get; set; }
        string Campo039 { get; set; }
        string Campo040 { get; set; }
        string Campo041 { get; set; }
        string Campo042 { get; set; }
        string Campo043 { get; set; }
        string Campo044 { get; set; }
        string Campo045 { get; set; }
        string Campo046 { get; set; }
        string Campo047 { get; set; }
        string Campo048 { get; set; }
        string Campo049 { get; set; }
        string Campo050 { get; set; }
        string Campo051 { get; set; }
        string Campo052 { get; set; }
        string Campo053 { get; set; }
        string Campo054 { get; set; }
        string Campo055 { get; set; }
        string Campo056 { get; set; }
        string Campo057 { get; set; }
        string Campo058 { get; set; }
        string Campo059 { get; set; }
        string Campo060 { get; set; }
        string Campo061 { get; set; }
        string Campo062 { get; set; }
        string Campo063 { get; set; }
        string Campo064 { get; set; }
        string Campo065 { get; set; }
        string Campo066 { get; set; }
        string Campo067 { get; set; }
        string Campo068 { get; set; }
        string Campo069 { get; set; }
        string Campo070 { get; set; }
        string Campo071 { get; set; }
        string Campo072 { get; set; }
        string Campo073 { get; set; }
        string Campo074 { get; set; }
        string Campo075 { get; set; }
        string Campo076 { get; set; }
        string Campo077 { get; set; }
        string Campo078 { get; set; }
        string Campo079 { get; set; }
        string Campo080 { get; set; }
        string Campo081 { get; set; }
        string Campo082 { get; set; }
        string Campo083 { get; set; }
        string Campo084 { get; set; }
        string Campo085 { get; set; }
        string Campo086 { get; set; }
        string Campo087 { get; set; }
        string Campo088 { get; set; }
        string Campo089 { get; set; }
        string Campo090 { get; set; }
        string Campo091 { get; set; }
        string Campo092 { get; set; }
        string Campo093 { get; set; }
        string Campo094 { get; set; }
        string Campo095 { get; set; }
        string Campo096 { get; set; }
        string Campo097 { get; set; }
        string Campo098 { get; set; }
        string Campo099 { get; set; }
        string Campo100 { get; set; }
        string Campo101 { get; set; }
        string Campo102 { get; set; }
        string Campo103 { get; set; }
        string Campo104 { get; set; }
        string Campo105 { get; set; }
        string Campo106 { get; set; }
        string Campo107 { get; set; }
        string Campo108 { get; set; }
        string Campo109 { get; set; }
        string Campo110 { get; set; }
        string Campo111 { get; set; }
        string Campo112 { get; set; }
        string Campo113 { get; set; }
        string Campo114 { get; set; }
        string Campo115 { get; set; }
        string Campo116 { get; set; }
        string Campo117 { get; set; }
        string Campo118 { get; set; }
        string Campo119 { get; set; }
        string Campo120 { get; set; }
        string Campo121 { get; set; }
        string Campo122 { get; set; }
        string Campo123 { get; set; }
        string Campo124 { get; set; }
        string Campo125 { get; set; }
        string Campo126 { get; set; }
        string Campo127 { get; set; }
        string Campo128 { get; set; }
        string Campo129 { get; set; }
        string Campo130 { get; set; }
        string Campo131 { get; set; }
        string Campo132 { get; set; }
        string Campo133 { get; set; }
        string Campo134 { get; set; }
        string Campo135 { get; set; }
        string Campo136 { get; set; }
        string Campo137 { get; set; }
        string Campo138 { get; set; }
        string Campo139 { get; set; }
        string Campo140 { get; set; }
    }
}
